# Generated by Django 2.0 on 2017-12-03 15:51

from django.db import migrations, models
import djiiif


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', djiiif.IIIFField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
